services:

  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "/c/etc/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/etc/selenoid/video:/opt/selenoid/video"
      - "/c/etc/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/etc/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8081:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  test_docker:
    build: .
    container_name: test_docker
    volumes:
      - ".:/app"
    depends_on:
      - selenoid
    networks:
      - selenoid
    tty: true
    command: ["pytest"]

networks:
  selenoid:
    name: selenoid
