services:

  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./config.json:/etc/selenoid/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/config.json", "-container-network", "selenoid"]

  test_docker:
    build: .
    container_name: test_docker
    depends_on:
      - selenoid
    networks:
      - selenoid
    tty: true
    command: ["pytest"]

networks:
  selenoid:
    name: selenoid
