# Файл ci.yml
# Имя workflow
name: Selenoid Test Workflow
# Перечень событий-триггеров, при которых должен запускаться workflow
on:
  # Событие push возникает,
  # когда изменения исходного кода приходят на сервер GitHub
  push:
    # Отслеживаем изменения только в ветке master
    branches:
      - master
# Перечень задач
jobs:
  run-tests-in-docker:
    runs-on: ubuntu-latest
    steps:
      # На GitHub Actions есть готовые описания шагов, 
      # их можно использовать в своих workflow.
      # Применим готовое описание шага для получения исходного кода
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0
      - name: Build docker images
        run: docker compose up --build --exit-code-from test_docker
